name: Singapore Girl in New York
favicon: null
layout_spectrum: 0.25550172314979136
typography_spectrum: 0.7988165642600507
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7787468144670129
  lightness: 0.9980356774758548
  saturation: 0.24884293810464442
  rhythmicContrast: 0.3376639673952013
purpose: []
